### ISSUE TITLE
Information Menu - Eastercamp

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#1]
Please change the menu item "Eastercamp" to "When/Where/Who"

**Comment by nicekiwi** [comment]
I disagree 100% with this idea as it adds no value, meaning or context for a visitor.

**Comment by SamPerry** [comment]
It narrows down what they are looking for, not just broad Eastercamp. Or another option "About Eastercamp" Eastercamp is just too broad

**Comment by nicekiwi** [comment]
_admits it makes more sense your way_

**Comment by SamPerry** [comment]
Actually it really needs "What" in there too. OR we make What another page and have a When/Where/Who page. Either option.

**Comment by nicekiwi** [comment]
Or we change it back to Eastercamp. Done.

On Sunday, 9 February 2014, SamPerry notifications@github.com wrote:

> Actually it really needs "What" in there too. OR we make What another page
> and have a When/Where/Who page. Either option.
> 
> On 8/02/2014, at 1:57 AM, Ezra Sharp <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > admits it makes more sense your way
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nicekiwi/southern-eastercamp/issues/1#issuecomment-34562821
> .

## 

Ezra Sharp
Creative Engineer

KiwiDev

Mobile: (022) 025-9918
Web: www.kiwidev.co.nz

**Comment by nicekiwi** [comment]
Or let's describe the entire pages contents in all the nav titles,
"register/costs/leavepasses"

On Sunday, 9 February 2014, Ezra Sharp ezra@kiwidev.co.nz wrote:

> Or we change it back to Eastercamp. Done.
> 
> On Sunday, 9 February 2014, SamPerry <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Actually it really needs "What" in there too. OR we make What another
> > page and have a When/Where/Who page. Either option.
> > 
> > On 8/02/2014, at 1:57 AM, Ezra Sharp notifications@github.com wrote:
> > 
> > > admits it makes more sense your way
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/nicekiwi/southern-eastercamp/issues/1#issuecomment-34562821
> > .
> 
> ## 
> 
> Ezra Sharp
> Creative Engineer
> 
> KiwiDev
> 
> Mobile: (022) 025-9918
> Web: www.kiwidev.co.nz

## 

Ezra Sharp
Creative Engineer

KiwiDev

Mobile: (022) 025-9918
Web: www.kiwidev.co.nz
