### ISSUE TITLE
Broken image reference on FAQ "How secure is Eastercamp?"

### ISSUE THREAD

**Issue by migrif** [nicekiwi/southern-eastercamp#11]
http://staging.eastercamp.org.nz/faq/question/5106 

Missing image

![screen shot 2014-02-09 at 7 38 30 pm](https://f.cloud.github.com/assets/5118567/2119242/d3ecd67a-9154-11e3-8627-1fe5149ec9ab.jpg)

Chrome OSX.

**Comment by migrif** [comment]
I know you're not looking for content errors, but it may come in useful when you do get the time to fix them :)

http://staging.eastercamp.org.nz/faq/question/5144

**Comment by SamPerry** [comment]
fixed
