### ISSUE TITLE
Images and video icons aren't loading

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#17]
[Windows]
Works in Firefox
Not working in Chrome, IE, Opera

[Fedora]
Works in Firefox
Not working in Chrome

[Android 4.4 - Nexus 4]
Not working in Chrome

When clicked, photos and videos go to url of asset.
Icon is acccessible directly - data-src url is accessible by going to it directly.

![image](https://f.cloud.github.com/assets/640597/2119248/05886ba8-9156-11e3-913e-ae8e1da63aee.png)

**Comment by hayatoc** [comment]
Found problem, this is stopping the rest of JS from being executed.
<b>Syntax error, unrecognized expression: [data-'Times New Roman'-abide]</b>

<code>$(document).foundation({
    tooltip : {
        disable_for_touch: true
    }
});</code>

https://github.com/zurb/foundation/issues/4371

**Comment by nicekiwi** [comment]
Cheers @hayatoc! :) Fixed!
