### ISSUE TITLE
Bottom Navigation Bar - stick to bottom

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#2]
Obviously still needs flashing up yet but can it stick to the bottom of the page regardless of content size. Looks wrong moving up.
![screen shot 2014-02-06 at 11 24 24 pm](https://f.cloud.github.com/assets/6603585/2097493/338b10e4-8f19-11e3-879a-5c0e50019180.png)

**Comment by nicekiwi** [comment]
Completed.
