### ISSUE TITLE
News page video thumbnails

### ISSUE THREAD

**Issue by pcm14** [nicekiwi/southern-eastercamp#21]
News page, the video thumbnails not loading, video works fine

**Comment by nicekiwi** [comment]
Can you more information? 

Device, link, screenshot etc?

**Comment by pcm14** [comment]
Have loaded now. No issue, maybe just a bit slow. Don't know if it's internet connection here or the amount of content issue

**Comment by nicekiwi** [comment]
Images will load as you scroll.
