### ISSUE TITLE
Probably need to add Tait logo to the sponsors 

### ISSUE THREAD

**Issue by georgewoofbates** [nicekiwi/southern-eastercamp#22]

**Comment by nicekiwi** [comment]
Who is Tait?

**Comment by georgewoofbates** [comment]
http://www.taitradio.com they are supplying media crew with radios

**Comment by georgewoofbates** [comment]
http://upload.wikimedia.org/wikipedia/en/7/70/Tait-Communications-logo.png

**Comment by SamPerry** [comment]
Its not Tait where the media crew ones are coming from. We have had all the Tait radios for years through our hookup, not through official ways from Tait and haven't had their logo up. I might see if they want it on there. But there is another company giving us radios which we might need to put up their logo. TBC

**Comment by georgewoofbates** [comment]
I actually managed to get some more radios donated to us through the company mount Campbell communications and they asked specifically that we put the tait logo and not theirs for some reason. I can check with them though if you like

**Comment by SamPerry** [comment]
Ah right, yeah let me know.

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz

**Comment by SamPerry** [comment]
Did you add one? Not sure if they want to link to Tait or Mount Campbell. The logo does need to be added though.

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz

**Comment by nicekiwi** [comment]
I do not have one. Add the details here if it is required.

**Comment by SamPerry** [comment]
Yet to find out which site it needs to link to.
George I believe you are the contact for Mount Campbell?

![tait-communications-logo](https://f.cloud.github.com/assets/6603585/2145392/37c0f14a-93a3-11e3-91a6-e05737de083b.png)

**Comment by georgewoofbates** [comment]
They are the dealers for all tait radios in Christchurch so they wanted to be linked back to tait website for some reason.

**Comment by nicekiwi** [comment]
Will be added in the 1.1 upgrade.
