### ISSUE TITLE
No links on top of Information page?

### ISSUE THREAD

**Issue by georgewoofbates** [nicekiwi/southern-eastercamp#24]
are there meant to be link at the top of this page http://staging.eastercamp.org.nz/information where it says When?Where?Who can go?

**Comment by SamPerry** [comment]
I added and anchor on when but it also added an anchor link on the When title. Ezra can you help on this?

**Comment by nicekiwi** [comment]
I'll just delete the text. its a shit design.

**Comment by SamPerry** [comment]
Ok yeah I don't care too much about that. Removed.

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz
