### ISSUE TITLE
Nothing in downloads folder

### ISSUE THREAD

**Issue by georgewoofbates** [nicekiwi/southern-eastercamp#27]
??

**Comment by nicekiwi** [comment]
Yeah.. there should be at least one.

**Comment by georgewoofbates** [comment]
this what looks like to me
![Uploading Screen Shot 2014-02-09 at 8.20.47 pm.png . . .]()

**Comment by georgewoofbates** [comment]
![screen shot 2014-02-09 at 8 20 49 pm](https://f.cloud.github.com/assets/6629403/2119299/ec3294f8-915a-11e3-8575-3e7b10705664.png)

**Comment by nicekiwi** [comment]
Yup.

**Comment by nicekiwi** [comment]
Fixed.
