### ISSUE TITLE
News Item String too long - min page width

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#28]
http://staging.eastercamp.org.nz/news?page=2

Browser gets horizontal scroll bars on mobile - I think it could be this:

URL is too long, longer than the page width on smaller devices

"Here's the official EC13 photo albums - get tagging! https://www.facebook.com/southerneastercamp/photos_albums"

![image](https://f.cloud.github.com/assets/640597/2119272/10292126-9159-11e3-8ff3-0a8bf5314d4a.png)

**Comment by nicekiwi** [comment]
Fixed.
