### ISSUE TITLE
Contact Page form location

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#3]
Can this form be at the top of the page. I added a title and some text but can't move the form.

**Comment by SamPerry** [comment]
Looks like I may have lost the purple in the bottom navigation bar with adding the text at the top..

**Comment by nicekiwi** [comment]
You want the form above all your text? 0_o;;

**Comment by SamPerry** [comment]
No sorry under that text I wrote. Above the address stuff. 

Sam Perry
Eastercamp 2014
Event Manager | Canterbury Youth Services
(Sent from small device, please excuse small errors)

**Comment by nicekiwi** [comment]
I'm gonna say no.

**Comment by SamPerry** [comment]
choice

**Comment by SamPerry** [comment]
I'm pushing back on this. We want people to use the form before they call us as the form can answer their questions, its a useful form you've made. So we want it at the top of the contact page as the first port of contact please.

**Comment by nicekiwi** [comment]
fine, but you wont be able to change to contact information.

**Comment by SamPerry** [comment]
Sorry what do you mean by that?

**Comment by nicekiwi** [comment]
I mean in the admin you will not be able to change the addresees, numbers etc yourself.

**Comment by SamPerry** [comment]
Oh right. Thats ok, I think they are all right now.

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz
