### ISSUE TITLE
Dropdown menus don't work

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#33]
Dropdown menus  don't... "drop down"

Windows: 
Doesn't work - Chrome, Firefox, Opera, IE

Fedora:
Doesn't work - Chrome, Firefox

![image](https://f.cloud.github.com/assets/640597/2119304/493f3d72-915b-11e3-8b4c-21285846ceb3.png)

**Comment by nicekiwi** [comment]
Duplicate of #14
