### ISSUE TITLE
Crash on wallpaper upload

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#35]
Crashed when I attempted to upload a wallpaper.
![2014-02-09 08 51 56 pm](https://f.cloud.github.com/assets/6603585/2119367/61599f66-915f-11e3-8192-545717a1a00c.jpg)

**Comment by nicekiwi** [comment]
Wallpapers Don't work atm.

**Comment by nicekiwi** [comment]
Add a wallpaper pack to the downloads.
