### ISSUE TITLE
Register link style

### ISSUE THREAD

**Issue by jacoblapworth** [nicekiwi/southern-eastercamp#38]
Should the register link in: http://staging.eastercamp.org.nz/information be the same style as seen in other locations?

![image](https://f.cloud.github.com/assets/6630254/2119674/d557d33c-917e-11e3-9dee-350f509f8310.png)
![image](https://f.cloud.github.com/assets/6630254/2119675/e06850da-917e-11e3-98a4-bc26b24d375a.png)

**Comment by nicekiwi** [comment]
funny that no one noticed the register link dosent work lol

**Comment by nicekiwi** [comment]
Fixed. I suspect @SamPerry deliberately pointed the link to the register page, but its quite unclear.
