### ISSUE TITLE
DSLR's - Gear list

### ISSUE THREAD

**Issue by jacoblapworth** [nicekiwi/southern-eastercamp#39]
Sorry not a bug - Content

We reckon a line for DLSR's in the gear list - discouraged gear would help: "Please leave your expensive camera's and DSLR's at home, we don't want them to break or be stolen and we have a great team of pro photographers to capture all your highlights at camp"

**Comment by nicekiwi** [comment]
Humble too..

**Comment by jacoblapworth** [comment]
Hahahahah we try ;)

**Comment by SamPerry** [comment]
haha very humble

**Comment by nicekiwi** [comment]
if not quite snobby..

**Comment by SamPerry** [comment]
Have put in "expensive cameras" that will do.
