### ISSUE TITLE
Info Eastercamp Page Pics

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#4]
Can we make the top pic a bit narrower. I'm not sold on only seeing the header and a few lines when you go to the page (on a 13inch which is common). I do like the chaining header pic though.

**Comment by nicekiwi** [comment]
Ignore the design.

**Comment by SamPerry** [comment]
Right ok.

Are you going to put some pics in-between the text like you did last year that lightbox from Facebook? Thats really good and livens up the site.

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz

**Comment by nicekiwi** [comment]
When you've finished changing the text, yup.

**Comment by SamPerry** [comment]
Ok cool beans

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz
