### ISSUE TITLE
[Minor] Photos and Videos are left-aligned on mobile

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#42]
Not sure if this was intentional, but photos and videos are left-aligned on small devices.

![image](https://f.cloud.github.com/assets/640597/2123490/23330ce8-922e-11e3-9b87-57e1989456dd.png)

**Comment by nicekiwi** [comment]
that is hardly a SMALL device..

**Comment by nicekiwi** [comment]
Fixed in next release.
