### ISSUE TITLE
Social Links missing?

### ISSUE THREAD

**Issue by hayatoc** [nicekiwi/southern-eastercamp#43]
No links to promote our Facebook, Twitter and YouTube from the website.

**Comment by SamPerry** [comment]
Keen for this to get done

**Comment by nicekiwi** [comment]
Oh are you indeed.

On Thursday, 27 February 2014, SamPerry notifications@github.com wrote:

> Keen for this to get done
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nicekiwi/southern-eastercamp/issues/43#issuecomment-36183346
> .

## 

Ezra Sharp
Creative Engineer

KiwiDev

Mobile: (022) 025-9918
Web: www.kiwidev.co.nz

**Comment by SamPerry** [comment]
Yes thank you my friend.

**Comment by nicekiwi** [comment]
Duplicate of #51
