### ISSUE TITLE
New Sponsor

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#55]
Hey can we add Telelift in the sponsors please. www.telelift.co.nz. Logo attached.
![telelift logo clr](https://f.cloud.github.com/assets/6603585/2241235/3fc96aca-9cc7-11e3-99ea-4ebed26ccefa.png)

**Comment by nicekiwi** [comment]
ha, didn't see this.

**Comment by nicekiwi** [comment]
Included in the next release.
