### ISSUE TITLE
News Menu Item Missing

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#8]
News menu item not there yet

**Comment by nicekiwi** [comment]
New feed looks like total shit at this size. Best not to have it till it can look decent. 

Should post all news on site and link post on Facebook. Syncing it up is bad. 

Goto /news if I want to see what's there.

**Comment by SamPerry** [comment]
Yeah I've gone to the URL. Its not that bad, just missing pics and then it would be sweet to me :)

Sam Perry
Event Coordinator

Eastercamp 2014
Canterbury Youth Services
MAIL  PO Box 5533 Papanui, Christchurch
PH  (03) 354 2181 
MOB  027 308 8235
WEB  eastercamp.org.nz

**Comment by nicekiwi** [comment]
It's worst with the pics

**Comment by nicekiwi** [comment]
A passible but still rubbish looking on desktop news feed is up.
