### ISSUE TITLE
Supporters Design

### ISSUE THREAD

**Issue by SamPerry** [nicekiwi/southern-eastercamp#9]
Personal preference I'd keep the colour in the logos.

Also could we maybe put a white rectangle across the section behind the logos as the white boxes on the grey doesn't look so flash.
![screen shot 2014-02-07 at 12 48 03 am](https://f.cloud.github.com/assets/6603585/2098037/a4a3d738-8f24-11e3-9935-0701e589d2c6.png)

**Comment by nicekiwi** [comment]
Background was originally white, will update the icons to match the new colour. 

Black and white icons will remain as the colours clash with the rest of the page. hovering over the images reveals the colour.

**Comment by SamPerry** [comment]
Ok sweet. 

And sure on hover over colour. 

Sam Perry
Eastercamp 2014
Event Manager | Canterbury Youth Services
(Sent from small device, please excuse small errors)
